-- Databricks notebook source
CREATE TABLE ecommerce.gold.customer_order_history (
  customer_unique_id STRING,
  customer_state STRING,
  customer_city STRING,
  total_orders BIGINT,
  delivered_orders BIGINT,
  late_orders BIGINT,
  avg_delivery_days DOUBLE,
  avg_delay_days DOUBLE,
  total_spend DECIMAL(38,18),
  avg_order_value DECIMAL(38,22),
  max_order_value DECIMAL(38,18),
  total_freight_paid DECIMAL(38,18),
  avg_pct_credit_card DECIMAL(38,22),
  installment_orders BIGINT,
  avg_installments DOUBLE,
  total_items_purchased BIGINT,
  avg_items_per_order DOUBLE,
  total_category_touches BIGINT,
  active_months BIGINT,
  avg_review_score DOUBLE,
  reviews_with_comment BIGINT,
  low_score_reviews BIGINT,
  first_order_date TIMESTAMP,
  last_order_date TIMESTAMP,
  customer_tenure_days INT,
  late_order_rate DOUBLE,
  avg_spend_per_month DECIMAL(23,2),
  freight_to_spend_ratio DECIMAL(37,4),
  creation_timestamp TIMESTAMP,
  updation_timestamp TIMESTAMP,
  job_run STRING,
  parent_job_run STRING)
USING delta
COLLATION 'UTF8_BINARY'
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7',
  'delta.parquet.compression.codec' = 'zstd')
