-- Databricks notebook source
CREATE TABLE ecommerce.gold.customer_features (
  customer_unique_id STRING,
  customer_state STRING,
  customer_city STRING,
  recency_days INT,
  frequency BIGINT,
  monetary DECIMAL(38,18),
  R_score INT,
  F_score INT,
  M_score INT,
  RFM_score INT,
  rfm_segment STRING,
  churn_label INT,
  clv_total_spend DECIMAL(38,18),
  clv_per_active_month DECIMAL(38,18),
  annualised_clv DECIMAL(38,18),
  clv_calculation_method STRING,
  clv_next_90d_estimate DECIMAL(38,18),
  avg_order_value DECIMAL(38,22),
  max_order_value DECIMAL(38,18),
  avg_delivery_days DECIMAL(38,18),
  avg_delay_days DOUBLE,
  late_order_rate DECIMAL(38,18),
  late_orders BIGINT,
  avg_review_score DECIMAL(38,18),
  low_score_reviews BIGINT,
  reviews_with_comment BIGINT,
  avg_pct_credit_card DECIMAL(38,22),
  avg_installments DOUBLE,
  installment_orders BIGINT,
  freight_to_spend_ratio DECIMAL(38,18),
  total_items_purchased BIGINT,
  avg_items_per_order DOUBLE,
  avg_categories_per_order DOUBLE,
  customer_tenure_days INT,
  active_months BIGINT,
  avg_spend_per_month DECIMAL(38,18),
  is_repeat_customer INT,
  first_order_date TIMESTAMP,
  last_order_date TIMESTAMP,
  creation_timestamp TIMESTAMP,
  updation_timestamp TIMESTAMP,
  job_run STRING,
  parent_job_run STRING)
USING delta
COLLATION 'UTF8_BINARY'
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7',
  'delta.parquet.compression.codec' = 'zstd')
